### ISSUE TITLE
Payara can't recover JDBC connections after SQL server disconnects for nightly backups

### ISSUE THREAD

**Issue by johnmanko** [payara/docker-payaramicro#65]
I have an image based on payara-micro:201 that can't seem to restore/reconnect it's JDBC connections after SQL Server disconnects for nightly backups.  I have to manually restart the containers each morning to reestablish those connects.  Comparatively, I run a non-Docker Payara Full on bare metal and it's able to recover just fine. Am I missing a "keep alive" configuration, or is this a bug with either docker-payaramicro or payaramicro?

Dockerfile:
```dockerfile
FROM payara/micro:latest

COPY services-1.0.0.war $DEPLOY_DIR

EXPOSE 8080 8181

CMD ["--deploymentDir", "/opt/payara/deployments", "--contextroot", "service"]
```

docker-compose.yml:
```yaml
version: '3'
services:   
  services:
    image: services:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
    env_file: services.env
    extra_hosts:
      - "sqlserver:192.168.1.5" 
    networks:
      - s_net                           

networks:
    s_net:
```
services.env:
```ini
S_DATABASE_NAME=Service
S_WORKSTATION=Stack
S_DATABASE_SERVER=sqlserver
S_DATABASE_USER=xxx
S_DATABASE_PASS=xxx
```
payara-resources.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//Payara.fish//DTD Payara Server 4 Resource Definitions//EN" "https://raw.githubusercontent.com/payara/Payara-Server-Documentation/master/schemas/payara-resources_1_6.dtd">
<resources>
    <jdbc-resource pool-name="ServicesDB" jndi-name="java:app/jdbc/service" enabled="true" ></jdbc-resource>

    <jdbc-connection-pool datasource-classname="com.microsoft.sqlserver.jdbc.SQLServerDataSource" 
                          name="ServicesDB" 
                          res-type="javax.sql.DataSource">
      <property name="User" value="${ENV=S_DATABASE_USER}"></property>
      <property name="Password" value="${ENV=S_DATABASE_PASS}"></property>
      <property name="DatabaseName" value="${ENV=S_DATABASE_NAME}"></property>
      <property name="ServerName" value="${ENV=S_DATABASE_SERVER}"></property>
      <property name="PortNumber" value="1433"></property>
    </jdbc-connection-pool>  
</resources>
```

Additionally, `msqsql-jdbc-7.0.0.jre8.jar` is a `compile` maven dependency, so it's in the `WEB-INF/lib` directory of the `war`.
